spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/openticon?stringtype=unspecified&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${LOCAL_NAME}
    password: ${LOCAL_PASSWORD}



server:
  port: 8080
  address: localhost

serverName: local_server
