spring:
  application:
    name: openticon
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        show_sql: true
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    fail-on-missing-locations: true

  sql:
    init:
      mode: always

  profiles:
    active: local

